// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDser4fVPtbu4CioHQcvSb-CvHT7arVxLM',
    appId: '1:1041522878948:web:38b9065e8919c155e2bff1',
    messagingSenderId: '1041522878948',
    projectId: 'cuci-mobil-dbacc',
    authDomain: 'cuci-mobil-dbacc.firebaseapp.com',
    storageBucket: 'cuci-mobil-dbacc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjS6PD_DTwtHuEStLwq0C1urwg9E-BbPg',
    appId: '1:1041522878948:android:4f32e491478d15b4e2bff1',
    messagingSenderId: '1041522878948',
    projectId: 'cuci-mobil-dbacc',
    storageBucket: 'cuci-mobil-dbacc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANJT6bq59R0yOgIICEwt97hznLUFOHrqg',
    appId: '1:1041522878948:ios:92c4b0dafe244a28e2bff1',
    messagingSenderId: '1041522878948',
    projectId: 'cuci-mobil-dbacc',
    storageBucket: 'cuci-mobil-dbacc.appspot.com',
    iosBundleId: 'com.example.cuciMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANJT6bq59R0yOgIICEwt97hznLUFOHrqg',
    appId: '1:1041522878948:ios:92c4b0dafe244a28e2bff1',
    messagingSenderId: '1041522878948',
    projectId: 'cuci-mobil-dbacc',
    storageBucket: 'cuci-mobil-dbacc.appspot.com',
    iosBundleId: 'com.example.cuciMobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDser4fVPtbu4CioHQcvSb-CvHT7arVxLM',
    appId: '1:1041522878948:web:e9d7c38632816269e2bff1',
    messagingSenderId: '1041522878948',
    projectId: 'cuci-mobil-dbacc',
    authDomain: 'cuci-mobil-dbacc.firebaseapp.com',
    storageBucket: 'cuci-mobil-dbacc.appspot.com',
  );

}